//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sick_Bay_Terminal_2019 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sick_Bay_Terminal_2019.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d446190b-740f-4ec3-b249-fc0b85f2ebbf.
        /// </summary>
        internal static string ClientId {
            get {
                return ResourceManager.GetString("ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string DebugFlag {
            get {
                return ResourceManager.GetString("DebugFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string IntervalSecondsClearControls {
            get {
                return ResourceManager.GetString("IntervalSecondsClearControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://joeysorg.onmicrosoft.com/WebApi/access_as_user.
        /// </summary>
        internal static string Scopes {
            get {
                return ResourceManager.GetString("Scopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 315c37fc-27dc-4021-9c67-a92e8878d455.
        /// </summary>
        internal static string Tenant {
            get {
                return ResourceManager.GetString("Tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEALTH_CENTRE1.
        /// </summary>
        internal static string TerminalCode {
            get {
                return ResourceManager.GetString("TerminalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://webapi.joeys.org.
        /// </summary>
        internal static string WebApiBaseAddress {
            get {
                return ResourceManager.GetString("WebApiBaseAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:5000.
        /// </summary>
        internal static string WebApiBaseAddress1 {
            get {
                return ResourceManager.GetString("WebApiBaseAddress1", resourceCulture);
            }
        }
    }
}
